services:
  eventstore.db:
    image: eventstore/eventstore:lts
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_NODE_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:2113/health/live || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3}
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      eventstore.db:
        condition: service_healthy
    environment:
      - EVENTSTORE_URI=http://admin:changeit@eventstore.db:2113
    command: tail -f /dev/null

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
